var DATA_SRC="./src/data/";
var DATA_FILE="./src/data.json";
var fs=require("fs");

var bigData={id:"com.agnibho.com.dietsurvey.data", timestamp: Date.now(), version: 0};
bigData.version=parseInt(new Date().toISOString().slice(0,10).replace(/-/g, ""))+0.1;

if(process.argv[2]=="watch"){
  fs.watch(DATA_SRC, jsonCat);
}
else{
  jsonCat();
}

function jsonCat(){
  bigData.rda=[];
  bigData.food=[];
  console.log("Joining JSON data files");
  try{
    bigData.rda=JSON.parse(fs.readFileSync(DATA_SRC+"rda.json"));
    bigData.food=JSON.parse(fs.readFileSync(DATA_SRC+"food.json"));
  }
  catch(e){
    console.log(e);
  }
  fs.writeFileSync(DATA_FILE, JSON.stringify(bigData), "utf8");
  console.log(DATA_FILE +" generated. Do not edit this file manually as it is overwritten on each build.");
}
